//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvyazhskieHills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int LoginHistoryID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Time { get; set; }
        public int LoginStatusID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LoginStatus LoginStatus { get; set; }
    }
}
